#!/bin/sh
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")

case `uname` in
    *CYGWIN*) basedir=`cygpath -w "$basedir"`;;
esac

if [ -z "$NODE_PATH" ]; then
  export NODE_PATH="/home/svmochalkina/.local/share/pnpm/global/5/.pnpm/standard-changelog@6.0.0_conventional-commits-filter@5.0.0/node_modules/standard-changelog/node_modules:/home/svmochalkina/.local/share/pnpm/global/5/.pnpm/standard-changelog@6.0.0_conventional-commits-filter@5.0.0/node_modules:/home/svmochalkina/.local/share/pnpm/global/5/.pnpm/node_modules"
else
  export NODE_PATH="/home/svmochalkina/.local/share/pnpm/global/5/.pnpm/standard-changelog@6.0.0_conventional-commits-filter@5.0.0/node_modules/standard-changelog/node_modules:/home/svmochalkina/.local/share/pnpm/global/5/.pnpm/standard-changelog@6.0.0_conventional-commits-filter@5.0.0/node_modules:/home/svmochalkina/.local/share/pnpm/global/5/.pnpm/node_modules:$NODE_PATH"
fi
if [ -x "$basedir/node" ]; then
  exec "$basedir/node"  "$basedir/global/5/node_modules/standard-changelog/cli.js" "$@"
else
  exec node  "$basedir/global/5/node_modules/standard-changelog/cli.js" "$@"
fi
